[package]
name = "rust"
version = "0.1.0"
authors = ["ballerina <ballerina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ballerinart"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.42"
