[project]
org-name = "ballerina"
version = "1.1.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "task"
    version = "1.1.0"
    path = "./lib/ballerina-task-1.1.0-java.jar"
    groupId = "ballerina"
    modules = ["task"]

    [[platform.libraries]]
    artifactId = "quartz"
    version = "2.3.1"
    path = "./lib/quartz-2.3.0.jar"
    groupId = "org.quartz-scheduler"
    modules = ["task"]
