[project]
org-name = "ballerina"
version = "0.8.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "observability"
    version = "0.8.0"
    path = "./lib/ballerina-observe-0.8.0-java.jar"
    groupId = "ballerina"
    modules = ["observe"]
