name: CI Ubuntu

on:
  pull_request:
    branches:
      - master
      - next-release
      - release-stage
      - stage
      - ballerina-1.2.x

jobs:
  ubuntu_build:
    name: Build without tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 75

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew build -x createJavadoc -x test --max-workers=2 --scan --no-daemon
          find ~/.gradle/caches/ -name "*.lock" -type f -delete 

  run_integration_test:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 75
    needs: ubuntu_build

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run integration test
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew :jballerina-integration-test:test --fail-fast -x createJavadoc --max-workers=1 --scan --no-daemon

  run_jbal_long_running_test:
    name: Run jbal & long running tests
    runs-on: ubuntu-latest
    timeout-minutes: 75
    needs: ubuntu_build

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run jballerina unit test
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew :jballerina-unit-test:test :testerina-integration-test:test --fail-fast -x createJavadoc --max-workers=1 --scan --no-daemon

  run_unit_test:
    name: Run all other unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 75
    needs: ubuntu_build

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run all the other unit test
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew build -x createJavadoc -x :jballerina-unit-test:test -x :jballerina-integration-test:test -x :testerina-integration-test:test --max-workers=1 --scan --no-daemon
